### ISSUE TITLE
Finalize internal API

### ISSUE THREAD

**Issue by MariusDieckmann** [ArunaStorage/DataProxy#1]
### Overview

Finalize the internal API and implement all associated calls.

### Tasks

- [x] Create upload ID
- [x] Get new (multipart) upload upload URL
- [x] Finalize upload
- [ ] Unit test functions

### Discussions
