### ISSUE TITLE
Config handling

### ISSUE THREAD

**Issue by MariusDieckmann** [ArunaStorage/DataProxy#2]
### Overview

Add config handling for the DataProxy component. Add YAML and environment variable support. Document the functionalities.

### Tasks

- [ ] YAML handling
- [ ] YAML documentation in README.md
- [ ] Environment variable handling
- [ ] Environment variable documentation in README.md

### Discussions

- Where should the associated S3 secrets be stored ?
