### ISSUE TITLE
[feat] CORS Configuration

### ISSUE THREAD

**Issue by St4NNi** [ArunaStorage/DataProxy#29]
## Problem

**Updated version for V2**

Integrating Aruna URL / S3 links into other websites is currently not possible because appropriate user-configurable CORS http headers are missing. Amazon S3 allows users to configure these per bucket via the [PutBucketCors](https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutBucketCors.html) requests.

Aruna should allow users to use this API, internally this would add CORS configuration labels to each collection. This way it would also be possible to configure CORS at ArunaAPI level.

### Todo

- [x] Wait for the upstream lib to allow for response header modifications (https://github.com/Nugine/s3s/issues/43).
- [x] Re-implement `PutBucketCORS` request, add CORS config as labels to project
- [x] Add configured CORS header to object responses

**Comment by St4NNi** [comment]
Fixed by #58
