### ISSUE TITLE
[feat] ListObjectV2

### ISSUE THREAD

**Issue by St4NNi** [ArunaStorage/DataProxy#32]
## ListObjectV2 S3 request

This request & associated responses lets users query S3 objects in buckets and group them via `delimiter` and `prefixes`.
[S3 docs](https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjectsV2.html).

We should support this request to make it easier to organize and list Aruna-S3 objects via virtual subfolders / subpaths.

### TODO:

- [x] Optimized subpath queries (relations table?), currently the query for specific subpaths / prefixes has some performance bottle necks that must be resolved before we can query 1000+ objects with prefixes
- [x] Add internal request for collection object queries with (sub) paths
- [ ] Implement necessary S3 call
