### ISSUE TITLE
Download multiple Objects

### ISSUE THREAD

**Issue by MariusDieckmann** [ArunaStorage/DataProxy#4]
### Overview

Implement download for multiple Objects / ObjectGroups or Collections as a single archive. This feature should allow users to pick a random collection of Resources and generate a single packed archive (e.g. `.tar.gz`). 

### Tasks

- [ ] Check if encryption@REST works for multipart upload
- [ ] Implement associated gRPC calls to create such URLs
- [ ] Test on the fly compression
- [ ] Add tests

### Discussions

- Does this work with encryption ?
- How should the gRPC calls work ?

**Comment by MariusDieckmann** [comment]
Check if encryption@REST works for multipart uploads.
